### ISSUE TITLE
i want to know where to download the raw *.gct files?

### ISSUE THREAD

**Issue by zihaoxingstudy1** [getzlab/CPTAC_PanCan_PTM_2023#1]
hello, i want to learn to analysis the cptac dataset from your notebook. but at first, i don't know where to download the raw data of the *.gct files in the step1. 
i want to know where to download the raw *.gct files? thanks a lot for your reply.
![cptac](https://github.com/getzlab/CPTAC_PanCan_PTM_2023/assets/58220227/9d6fda8d-e0e0-4631-b65b-234ee1ef3d9a)

**Comment by shankara-a** [comment]
Hi - thanks for reaching out. Raw **.gct** files may be downloaded from the [proteomic data commons](https://proteomic.datacommons.cancer.gov/pdc/publications). Please let me know if you have further questions!
