### ISSUE TITLE
Can not  find the data, results could not be validated 

### ISSUE THREAD

**Issue by Ansanqi** [getzlab/CPTAC_PanCan_PTM_2023#2]
where I can download these data？
CPTAC_REFSEQ_FASTA = "../../data/ref/genomic/RefSeq.20180629_Human_ucsc_hg38_cpdbnr_mito_264contams_553smORFs.fasta"
CPTAC_FEATURE_FILE = "../../data/processed/061721/var_map_full.tsv"
DATA_DIR = "../../data/processed/061721"

**Comment by shankara-a** [comment]
Hi, thank you for your interest in this project.

1. The reference `fasta` for this CPTAC project is now included under **reference** in the [data directory](https://github.com/getzlab/CPTAC_PanCan_PTM_2023/tree/master/data) along with a [ReadMe](https://github.com/getzlab/CPTAC_PanCan_PTM_2023/blob/master/data/reference/Readme_RefSeq.20180629.txt) that describes how it was generated.
2. The feature file includes all CPTAC molecular features (RNA, proteome, PTM) used for clustering & downstream analyses. The latest version of this may also be found in under **reference** in the [data directory](https://github.com/getzlab/CPTAC_PanCan_PTM_2023/tree/master/data) as `var_map_full_v4.tsv`.
3. This processed data directory is an intermediate directory created when processing the raw proteomic data that needs to be downloaded by the [proteomic data commons](https://proteomic.datacommons.cancer.gov/pdc/publications). It is specifically generated by [this notebook](https://github.com/getzlab/CPTAC_PanCan_PTM_2023/blob/master/Fig1/01a_process_proteomics.ipynb).

Please let me know if you have any further questions!

Shankara
